[package]
name = "init"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "_init"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ulib = {path = "../ulib"}